language: java
sudo: false
install: true

script:
  - mvn clean package
  - mvn sonar:sonar -Dsonar.projectKey=pictureperfectapp_PPBackEnd -Dsonar.organization=pictureperfectapp -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_TOKEN